name: CI

on:
  push:
    branches:
      - dev
      - auto/clang-tidy
  pull_request:
  release:
    types:
      - created

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      shell: bash
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
    - name: check submodules
      run: ./source/scripts/check_submodules.sh

  build:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            docker_image: [azhicham/debian8_dev, azhicham/debian9_dev, azhicham/debian10_dev, navitia/debian11_dev]

    container:
        image: ${{matrix.docker_image}}

    services:
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672

      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'recursive'
    - name: configure for Release
      run: mkdir build && cd ./build && cmake -DSTRIP_SYMBOLS=ON ../source
    - name: run
      working-directory: ./build
      run: make -j $(nproc)
    - name: Tests python2
      working-directory: ./build
      run: |
        pip install virtualenv==20.4.7 -U
        virtualenv -p python2.7 navitia_py2
        . navitia_py2/bin/activate
        pip install -r ../source/jormungandr/requirements_dev.txt
        export JORMUNGANDR_BROKER_URL='amqp://guest:guest@rabbitmq:5672//'
        export KRAKEN_RABBITMQ_HOST='rabbitmq'
        ctest --output-on-failure
    - name: Tests python3.9
      working-directory: ./build
      run: |
        virtualenv -p python3.9 navitia_py3
        . navitia_py3/bin/activate
        pip install -r ../source/jormungandr/requirements_dev.txt
        export JORMUNGANDR_BROKER_URL='amqp://guest:guest@rabbitmq:5672//'
        export KRAKEN_RABBITMQ_HOST='rabbitmq'
        ctest --output-on-failure
        deactivate
    - name: docker_test for python2
      working-directory: ./build
      run: |
        . navitia_py2/bin/activate
        pip install -r ../source/tyr/requirements_dev.txt
        pip install -r ../source/sql/requirements.txt
        export NAVITIA_CHAOS_DUMP_PATH=$(echo $GITHUB_WORKSPACE/source/tests/chaos/chaos_loading.sql.gz | sed -e 's#__w#home/runner/work#')
        echo $NAVITIA_CHAOS_DUMP_PATH
        make docker_test
      env:
        NAVITIA_DOCKER_NETWORK: ${{ job.container.network }}
        TYR_CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'
        TYR_REDIS_HOST: 'redis'
    - name: docker_test for python3.9
      working-directory: ./build
      run: |
        . navitia_py3/bin/activate
        pip install -r ../source/tyr/requirements_dev.txt
        pip install -r ../source/sql/requirements.txt
        export NAVITIA_CHAOS_DUMP_PATH=$(echo $GITHUB_WORKSPACE/source/tests/chaos/chaos_loading.sql.gz | sed -e 's#__w#home/runner/work#')
        echo $NAVITIA_CHAOS_DUMP_PATH
        make docker_test
      env:
        NAVITIA_DOCKER_NETWORK: ${{ job.container.network }}
        TYR_CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'
        TYR_REDIS_HOST: 'redis'

  precommit:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
      # we need python 3.6 and clang-format-6.0
      # we should be able to use no container once https://github.com/actions/virtual-environments/issues/46 is
      # resolved
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        apt update && apt install -y protobuf-compiler python python-pip python3  python3-pip clang-format-6.0 git 2to3
        pip install -r requirements_pre-commit.txt --upgrade
    - name: get submodule
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
    - name: Build Protobuf
      run: bash source/scripts/build_protobuf.sh
    - name: Pre-commit Run
      env:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      run: |
        pre-commit install --install-hooks
        pre-commit run --all --show-diff-on-failure
  release_script_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - uses: actions/checkout@v2
    - uses: dschep/install-pipenv-action@v1
    - name: Setup Pipenv and Run tests
      working-directory: release
      env:
        GIT_PYTHON_REFRESH: quiet
      run: |
        pipenv install --dev
        pipenv run pytest
        pipenv --rm
